"""empty message

Revision ID: bd72cd2db121
Revises: fec79f359fc8
Create Date: 2020-11-05 16:16:49.254154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd72cd2db121'
down_revision = 'fec79f359fc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('pemail', sa.String(length=50), nullable=True))
    op.drop_column('teacher', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('student', 'pemail')
    # ### end Alembic commands ###
