"""classroom table

Revision ID: f42d5233d82a
Revises: b569a4ef4ce3
Create Date: 2020-08-17 13:56:27.092863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f42d5233d82a'
down_revision = 'b569a4ef4ce3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classroom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classes', sa.String(length=64), nullable=True),
    sa.Column('Teacher', sa.Integer(), nullable=True),
    sa.Column('Students', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Students'], ['student.id'], ),
    sa.ForeignKeyConstraint(['Teacher'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classroom_classes'), 'classroom', ['classes'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classroom_classes'), table_name='classroom')
    op.drop_table('classroom')
    # ### end Alembic commands ###
