"""empty message

Revision ID: fec79f359fc8
Revises: f00c349afbf4
Create Date: 2020-11-04 12:09:48.988603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fec79f359fc8'
down_revision = 'f00c349afbf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('subject', sa.String(length=20), nullable=True))
    op.drop_column('teacher', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('student', 'subject')
    # ### end Alembic commands ###
